### ISSUE TITLE
Gnome Shell Can't Detect Dedicated Graphics Card.

### ISSUE THREAD

**Issue by Superdanby** [Superdanby/Grub-Nvidia-Entry#2]
Gnome shell can't detect the dGPU. Consequently, the option "Launch using Dedicated Graphics Card" in Gnome's right click menu is not shown.
Nouveau is being loaded correctly. It is tested with `DRI_PRIME=1 glxgears -info`.

System information:
Secure Boot: On
Kernel: 4.15.4-300.fc27.x86_64
Gnome: 3.26.2
Mode: Intel + Nouveau

How reproducible: 100%

Actual results:
Gnome not detecting dGPU.

Expected results:
![image](https://user-images.githubusercontent.com/17717083/36631627-8112a01c-19b6-11e8-845d-4db468726192.png)
![image](https://user-images.githubusercontent.com/17717083/36631645-d2c69328-19b6-11e8-97fc-3106805eb5d6.png)

Additional information:
This problem has existed from kernel 4.13 at least.

**Comment by Superdanby** [comment]
After searching for a looong time, it turns out that switcheroo-control is the main culprit. Gnome [requires switcheroo-control](http://www.hadess.net/2016/10/dual-gpu-integration-in-gnome.html) to detect dGPU, but there is [something wrong with vgaswitcheroo when Secure Boot is on](https://bugzilla.redhat.com/show_bug.cgi?id=1476366#c2). So, the switcheroo-control service failed.

The only solution now is to turn off Secure Boot.

After turning off Secure Boot, switcheroo-control service may still failed to activate on startup. A workaround is to set `Restart=on-success` in `/usr/lib/systemd/system/switcheroo-control.service`.

**Comment by pk044** [comment]
still doesn't work on gnome - worked previously on kde, switched to gnome on the same setup and it doesn't run nvidia anymore :(

**Comment by Superdanby** [comment]
I guess your issue is different from this one. Could you open a new issue and give a more detailed description of your problem? For example, not seeing the grub entry. Also, please post the output of `systemctl status grub-nvidia-entry`.
