### ISSUE TITLE
No entry added

### ISSUE THREAD

**Issue by benjaminvatterj** [Superdanby/Grub-Nvidia-Entry#8]
Hi,

I cloned the repository and tried both "make enable" and "make" but no entry was added to grub on reboot. The service however seems to be running, yet Nvidia is running. 
I'm running Fedora 28 Gnome Version 3.28.2 on Dell XPS 15 9560.
I'm not really sure how to debug this, so please let me know what information I can add that can be useful. 

Thanks!

**Comment by Superdanby** [comment]
If the service is working flawlessly, you should see the following with `systemctl status grub-nvidia-entry.service`.
![screenshot from 2018-06-29 14-10-12](https://user-images.githubusercontent.com/17717083/42076292-23f46354-7ba7-11e8-8a83-f44c7f2c6aaf.png)
Please upload the screenshot of `systemctl status grub-nvidia-entry.service` if it doesn't look like the above.

You can also check the contents of `/etc/grub.d/40_custom`. It should look like:
![image](https://user-images.githubusercontent.com/17717083/42076652-974e9508-7ba8-11e8-972e-09fdb451101d.png)

Lastly, make sure you can run the `grub2-mkconfig` command.
![image](https://user-images.githubusercontent.com/17717083/42076811-44c094e8-7ba9-11e8-9344-7810c9841d04.png)

If all of the above look the same, running [`sudo grub2-mkconfig -o /boot/efi/EFI/fedora/grub.cfg`](https://github.com/Superdanby/Grub-Nvidia-Entry/blob/master/grub-nvidia-entry.sh#L70) should produce an entry in the grub menu.

Let me know if you encountered any problems.

**Comment by benjaminvatterj** [comment]
thanks for the reply, so I think it might be working but I cant recognize the menu entry. 
So "make enable" wasnt enough for making the daemon working, so I had to do "make" after that. 
This is the status of the service
![systemctl](https://user-images.githubusercontent.com/16083768/42092923-3d9525aa-7b70-11e8-91fd-705c2d09fa74.png)
and this is the 40_custom file afterwards
![40custom](https://user-images.githubusercontent.com/16083768/42092940-47e47042-7b70-11e8-8706-3f50aa07198b.png)
But these are the grub entries, in which I don't know which am I supose to use
![entries](https://user-images.githubusercontent.com/16083768/42092964-63e0a266-7b70-11e8-98aa-eec484e81797.png)
Also, how do I know which graphics am I running right now? I think I might have nvidia turned off right now
![screenshot from 2018-06-29 07-47-00](https://user-images.githubusercontent.com/16083768/42093053-a9a7683e-7b70-11e8-83f9-070040db2d6a.png)

**Comment by Superdanby** [comment]
Ok, so it works like this.
If you run `make enable`, the service is registered immediately. On the next boot, the service will be activated by Systemd. This is when the new settings are configured. And then, you'll have to reboot again to see the settings.

0 -> `make enable`
1 -> `grub-nvidia-entry.serivce` starts running
2 -> new entry appears

To bridge this gap, you can run `make`. And the new settings will be applied right away. Hence you'll be able to see the new entry on the next boot.

0 -> `make`
1 -> new entry appears

---

For Nouveau, pick the ones with `modprobe.blacklist=nvidia,nvidia_drm,nvidia_modeset,nvidia_uvm`.

For the proprietary Nvidia drivers,
pick the one with `rd.driver.blacklist=nouveau modprobe.blacklist=nouveau nvidia-drm.modeset=1`. Usually, this one will be the last Fedora entry.

---

Verifying the drivers:

Under Intel/Nouveau:
iGPU: `glxgears -info | grep GL_VENDOR`
![image](https://user-images.githubusercontent.com/17717083/42094545-b2c5d6e0-7be2-11e8-96ac-c02493e5aeb9.png)
dGPU(Nouveau): `DRI_PRIME=1 glxgears -info | grep GL_VENDOR`
![image](https://user-images.githubusercontent.com/17717083/42094513-9a635e60-7be2-11e8-856d-107b64721851.png)

Under Intel/Nvidia: `glxgears -info | grep GL_VENDOR`
![image](https://user-images.githubusercontent.com/17717083/42094950-d1ee623e-7be3-11e8-80c8-77f8209318ba.png)

---

Hope this helps. And thanks for the feedback.
I'll make some improvements on both the documentation and the ambiguous entry name if I have time.

**Comment by benjaminvatterj** [comment]
Awesome. thanks!

**Comment by Superdanby** [comment]
Closed by  https://github.com/Superdanby/Grub-Nvidia-Entry/commit/bfb8cd4563f0ec9f06b186a0c294f7d9f9a2fd1f.
